server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security:
          oauth2: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
