spring:
  security:
    user:
      name: admin
      password: password
  cloud:
    gateway:
      routes:
        - id: server
          uri: http://localhost:8081
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix=1
        - id: client
          uri: http://localhost:5173
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0
